definitions:
  routes.SignupRequest:
    properties:
      password:
        example: senha_forte_123
        type: string
      username:
        example: operador_01
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Valida credenciais e retorna JWT com permissões estilo Discord
      parameters:
      - description: Credenciais
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.SignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Credenciais inválidas
          schema:
            type: string
      summary: Login do usuário
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Cria uma conta e atribui o grupo padrão 'Membro' via transação
      parameters:
      - description: Dados de cadastro
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário criado com sucesso
          schema:
            type: string
        "400":
          description: Dados inválidos
          schema:
            type: string
      summary: Cadastro de novo usuário
      tags:
      - Auth
swagger: "2.0"
