definitions:
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  routes.authResponse:
    properties:
      message:
        type: string
    type: object
  routes.registerRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Recebe credenciais e retorna um JWT com as permissões do usuário
      parameters:
      - description: Credenciais de Login
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 'token: <jwt_token>'
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Credenciais inválidas
          schema:
            type: string
      summary: Realiza o login do usuário
      tags:
      - Auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Invalida o token ou revoga a sessão do usuário autenticado
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.authResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/routes.authResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/routes.authResponse'
      summary: Encerra a sessão do usuário
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Cria uma nova conta de usuário a partir das credenciais fornecidas
      parameters:
      - description: Dados de registro
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.registerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/routes.authResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/routes.authResponse'
        "405":
          description: Method Not Allowed
          schema:
            $ref: '#/definitions/routes.authResponse'
      summary: Registra novo usuário
      tags:
      - Auth
swagger: "2.0"
